
---
  - name: Jenkins_setting_sber2
    hosts: sber2
    become: yes

    tasks:


     - name: Test
       shell: ping -c 5 8.8.8.8
       register: ping
       
     - name: Who
       shell: hostname
       register: name
       
     - name: Output1
       debug:
         var: ping
   
     - name: Output2
       debug:
         var: name